package com.example.fxtradesample;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table INSTRUMENT.
*/
public class InstrumentDao extends AbstractDao<Instrument, Long> {

    public static final String TABLENAME = "INSTRUMENT";

    /**
     * Properties of entity Instrument.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "_id");
        public final static Property Instrument = new Property(1, String.class, "displayName", false, "DISPLAYNAME");
    };


    public InstrumentDao(DaoConfig config) {
        super(config);
    }
    
    public InstrumentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'INSTRUMENT' (" + //
                "'_id' TEXT PRIMARY KEY ," + // 0: id
                "'DISPLAYNAME' TEXT);"); // 1: instrument
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DISPLAYNAME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Instrument entity) {
        stmt.clearBindings();
 
        String id = entity.instrument();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String instrument = entity.displayName();
        if (instrument != null) {
            stmt.bindString(2, instrument);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Instrument readEntity(Cursor cursor, int offset) {
        Instrument entity = new Instrument( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // instrument
                null,
                null,
                0
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Instrument entity, int offset) {
//        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
//        entity.setInstrument(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Instrument entity, long rowId) {
//        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Instrument entity) {
        if(entity != null) {
            return null;
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
